read_cv_task:
  description: >
    FIRST STAGE: Initial CV Analysis
    Extract and categorize basic information from all CVs to enable efficient matching.
    Focus on:
    1. Technical Skills (list all technical skills mentioned)
    2. Role Experience (list all roles held)
    3. Key Achievements (list major accomplishments)
    4. Years of Experience (in each role)
    5. Education and Certifications

    {cv_files}
  expected_output: >
    A structured summary of all CVs in this format:
    
    CV: [Filename]
    Technical Skills: [List of all technical skills]
    Role Experience: [List of roles with years]
    Key Achievements: [List of major accomplishments]
    Education: [List of degrees and certifications]
    
    [Repeat for each CV]

filter_candidates_task:
  description: >
    SECOND STAGE: Initial Filtering
    For each job role, identify potential candidates based on basic criteria.
    Use the following quick filters:
    
    1. Software Engineer:
       - Has coding experience
       - Knows relevant programming languages
    
    2. Software Architect:
       - Has system design experience
       - Has technical leadership experience
    
    3. Project Manager:
       - Has project management experience
       - Has team leadership experience
    
    4. DevOps Engineer:
       - Has infrastructure experience
       - Has automation experience
    
    5. QA Engineer:
       - Has testing experience
       - Has quality assurance experience
    
    6. Business Analyst:
       - Has requirements analysis experience
       - Has stakeholder management experience
    
    For each role, list up to 3 potential candidates that meet the basic criteria.
    Include a brief explanation of why they might be suitable.

    Jobs CSV file: {path_to_jobs_csv}
    {cv_files}
  expected_output: >
    For each job role, list up to 3 potential candidates:
    
    Job: [Job Title]
    Potential Candidates:
    1. [Candidate Name]
       - Basic Match: [Brief explanation]
    2. [Candidate Name]
       - Basic Match: [Brief explanation]
    3. [Candidate Name]
       - Basic Match: [Brief explanation]
    
    [Repeat for each job role]

match_cv_task:
  description: >
    FINAL STAGE: Detailed Matching
    For each job role, perform detailed analysis of the pre-filtered candidates
    to identify the single most suitable candidate.
    
    Use the following detailed criteria:

    For Software Engineer roles:
    - Hands-on coding experience and proficiency
    - Implementation and development skills
    - Experience with specific programming languages and frameworks
    - Track record of delivering working software
    - Focus on technical execution and problem-solving
    - PREFERRED: Direct software development experience
    - CAN BE: Related technical roles with coding experience
    - CONSIDER: Technical roles with problem-solving skills

    For Software Architect roles:
    - System design and architecture experience
    - Experience with high-level technical decisions
    - Track record of designing scalable systems
    - Experience with technical leadership
    - Focus on system-level thinking and design patterns
    - PREFERRED: Direct architecture experience
    - CAN BE: Senior technical roles with design experience
    - CONSIDER: Technical roles with system thinking

    For QA Engineer roles:
    - Test planning and execution experience
    - Experience with testing methodologies and tools
    - Knowledge of test automation frameworks
    - Experience with bug tracking and reporting
    - Understanding of software development lifecycle
    - PREFERRED: Direct QA/testing experience
    - CAN BE: Related roles with strong testing skills
    - CONSIDER: Technical roles with attention to detail

    For DevOps Engineer roles:
    - CI/CD pipeline experience
    - Infrastructure automation experience
    - Container orchestration knowledge
    - Monitoring and logging experience
    - Cloud platform expertise
    - PREFERRED: Direct DevOps experience
    - CAN BE: Related technical roles with automation experience
    - CONSIDER: Technical roles with system administration experience

    For Project Manager roles:
    - Project management methodology experience
    - Team leadership and coordination
    - Budget and timeline management
    - Stakeholder communication
    - Risk management experience
    - PREFERRED: Direct project management experience
    - CAN BE: Related roles with strong leadership experience
    - CONSIDER: Technical roles with team coordination experience

    For Business Analyst roles:
    - Requirements gathering and analysis
    - Process improvement experience
    - Stakeholder management
    - Documentation skills
    - Business process understanding
    - PREFERRED: Direct business analysis experience
    - CAN BE: Related roles with strong analysis skills
    - CONSIDER: Technical roles with strong communication skills

    Jobs CSV file: {path_to_jobs_csv}
    {cv_files}
  expected_output: >
    REQUIRED OUTPUT FORMAT:
    
    Job Title: [Job Name]
    Top Candidate: [Candidate Name]
    - Match Score: [High/Medium/Low]
    - Key Matching Points: [List of relevant skills and experience]
    - Areas of Misalignment: [If any]
    - Role-Specific Strengths: [List specific strengths for this particular role]
    - Experience Quality: [Evaluate the specificity and relevance of experience]
    - Direct Experience: [Yes/No - Does candidate have direct experience in this role?]
    - Role Alignment: [Explain why this candidate's experience aligns with this specific role]
    - Scoring Justification: [Explain the scoring based on the scoring system]
    - Growth Potential: [Evaluate candidate's potential to grow in this role]
    
    [REPEAT THIS FORMAT FOR EVERY JOB IN THE JOBS.CSV FILE]
    
    IMPORTANT:
    - You must include ALL jobs from the jobs.csv file
    - For each job, show exactly one candidate, the most suitable one
    - The output must be organized by job, not by candidate
    - Do not skip any jobs from the jobs.csv file
    - Consider both direct experience and transferable skills
    - Look for candidates with potential to grow into the role
    - Consider complementary skills that could be valuable
    - Apply the scoring system to all candidates
    - Consider both technical and soft skills
    - You must process and show results for ALL jobs in the jobs.csv file
    - You must show results for ALL of these jobs: Software Engineer, Software Architect, Project Manager, DevOps Engineer, QA Engineer, Business Analyst
  output_file: output/decision.md
