read_cv_task:
  description: >
    Extract relevant information from all three CVs. Focus on skills, experience,
    education, and key achievements.
    Ensure to capture each candidate's professional summary, technical skills,
    work history, and educational background.

    First CV file: {path_to_cv}
    Second CV file: {path_to_cv2}
    Third CV file: {path_to_cv3}
  expected_output: >
    A structured summary of all three CVs, including for each:
    - Professional Summary
    - Technical Skills
    - Work History
    - Education
    - Key Achievements

match_cv_task:
  description: >
    IMPORTANT: You must analyze ALL jobs from the jobs.csv file and for EACH job,
    identify and rank the top two most suitable candidates from the three CVs.
    
    The output MUST be organized by job, with each job showing its top two candidates
    in order of suitability. You must include ALL jobs from the jobs.csv file.
    
    For each job-candidate match, evaluate based on:
    - Skills alignment
    - Experience relevance
    - Key achievements
    - Overall fit for the role

    Jobs CSV file: {path_to_jobs_csv}
    First CV file: {path_to_cv}
    Second CV file: {path_to_cv2}
    Third CV file: {path_to_cv3}
  expected_output: >
    REQUIRED OUTPUT FORMAT:
    
    Job Title: [Job Name]
    1. [Top Candidate Name]
       - Match Score: [High/Medium/Low]
       - Key Matching Points: [List of relevant skills and experience]
       - Areas of Misalignment: [If any]
    
    2. [Second Best Candidate Name]
       - Match Score: [High/Medium/Low]
       - Key Matching Points: [List of relevant skills and experience]
       - Areas of Misalignment: [If any]
    
    [REPEAT THIS FORMAT FOR EVERY JOB IN THE JOBS.CSV FILE]
    
    IMPORTANT:
    - You must include ALL jobs from the jobs.csv file
    - For each job, show exactly two candidates, ranked by suitability
    - The output must be organized by job, not by candidate
    - Do not skip any jobs from the jobs.csv file
  output_file: output/decision.md
